In [1]:
import sys
sys.path.append('..')
import SRNF_match
import H2_match as gm
import utils.input_output as input_output
import numpy as np
import torch
use_cuda = 1
torchdeviceId = torch.device('cuda:0') if use_cuda else 'cpu'
torchdtype = torch.float32

/home/emanuel/anaconda3/envs/varidist/lib/python3.7/site-packages/pykeops/torch/kernel_product/__init__.py:6: DeprecationWarning: [pyKeOps]: the kernel_product syntax is deprecated. Please consider using the LazyTensor helper instead.
  DeprecationWarning,


In [2]:
N=2 
[VS,FS,FunS] = input_output.loadData("TestData/faces/face-reference.ply")  
VS=VS/10
[VS,FS]= input_output.decimate_mesh(VS,FS,int(FS.shape[0]/16))   
FunS=np.zeros((int(np.size(VS)/3),)) 
sources = [[VS,FS]]

[VT,FT,FunT] = input_output.loadData("TestData/faces/face-rage.ply") 
VT=VT/10
[VT,FT]= input_output.decimate_mesh(VT,FT,int(FT.shape[0]/16))
FunT=np.zeros((int(np.size(VT)/3),)) 
targets= [[VT,FT]]

source=sources[0] 
target=targets[0]

/home/emanuel/anaconda3/envs/varidist/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [3]:
a0=.01
a1=100
b1=100
c1=.2
d1=.01
a2=.01


param1 = { 'weight_coef_dist_T': 10**1,'weight_coef_dist_S': 10**1,'sig_geom':.4,\
          'max_iter': 2000,'time_steps': 2, 'tri_unsample': True, 'index':0}

param2 = {'weight_coef_dist_T': 10**2,'weight_coef_dist_S': 10**2,'sig_geom':.3,\
          'max_iter': 1000,'time_steps': 2, 'tri_unsample': False, 'index':1}

param3 = {'weight_coef_dist_T': 10**3,'weight_coef_dist_S': 10**3,'sig_geom':.2,\
          'max_iter': 1000, 'time_steps': 2, 'tri_unsample': False, 'index':1}

param4 = {'weight_coef_dist_T': 10**4,'weight_coef_dist_S': 10**4,'sig_geom':.1,\
          'max_iter': 1000, 'time_steps': 3, 'tri_unsample': True, 'index':1}

param5 = {'weight_coef_dist_T': 10**5,'weight_coef_dist_S': 10**5,'sig_geom':.1,\
          'max_iter': 1000, 'time_steps': 4, 'tri_unsample': False, 'index':2}

param6 = { 'weight_coef_dist_T': 10**6,'weight_coef_dist_S': 10**6,'sig_geom':.05,\
          'max_iter': 1000, 'time_steps': 5, 'tri_unsample': False, 'index':2}



paramlist=[param1,param2,param3,param4,param5,param6]

In [4]:
geod,F0=gm.H2MultiRes(source,target,a0,a1,b1,c1,d1,a2,2,paramlist)

(3614, 3)
(903, 3)
(225, 3)
tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [Fa

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
        

KeyboardInterrupt: 

In [ ]:
input_output.plotGeodesic(geod,F0,source=source,target=target, file_name='results/faces',stepsize=2, axis=[0,0,1],angle=-1*np.pi)

In [ ]:
import numpy as np
import scipy
xp=np.linspace(0,1,5,endpoint=True)
x=np.linspace(0,1,60,endpoint=True)    
f=scipy.interpolate.interp1d(xp,geod,axis=0)
geod=f(x)
for i in range(0,geod.shape[0]):
    input_output.plotGeodesic([geod[i]],F0,stepsize=5,file_name='results/gif/faces{}'.format(i),axis=[0,1,0],angle=-1*np.pi/2)